
const ort = require('onnxruntime-web');
const fs = require('fs');
const path = require('path');

// Load sample data generated by Python
const sampleDataPath = path.join(__dirname, 'sample_data.json');
const sampleData = JSON.parse(fs.readFileSync(sampleDataPath, 'utf8'));

// Convert Python list to Float32Array for ONNX Runtime
function toFloat32Array(arr) {
    return Float32Array.from(arr.flat(Infinity));
}

// Helper to compare arrays with a tolerance
function arraysClose(arr1, arr2, rtol = 1e-5, atol = 1e-5) {
    if (arr1.length !== arr2.length) {
        return false;
    }
    for (let i = 0; i < arr1.length; i++) {
        if (Math.abs(arr1[i] - arr2[i]) > (atol + rtol * Math.abs(arr2[i]))) {
            return false;
        }
    }
    return true;
}

describe('MotionGenerator_RNN ONNX Model', () => {
    let session;

    beforeAll(async () => {
        // Load the ONNX model
        const modelPath = path.join(__dirname, 'motion_generator.onnx');
        session = await ort.InferenceSession.create(modelPath);
    });

    test('should produce output close to Python reference', async () => {
        const audInputShape = session.inputMetadata.find(input => input.name === 'aud_input').shape.map(dim => {
            if (dim === 'batch_size') return 1;
            if (dim === 'sequence_length') return 100;
            return dim;
        });
        const moInputShape = session.inputMetadata.find(input => input.name === 'mo_input').shape.map(dim => {
            if (dim === 'batch_size') return 1;
            if (dim === 'sequence_length') return 100;
            return dim;
        });
        const lxmInputShape = session.inputMetadata.find(input => input.name === 'lxm_input').shape.map(dim => {
            if (dim === 'batch_size') return 1;
            if (dim === 'num_blocks') return 10;
            return dim;
        });

        const audInput = new ort.Tensor('float32', toFloat32Array(sampleData.aud_input), audInputShape);
        const moInput = new ort.Tensor('float32', toFloat32Array(sampleData.mo_input), moInputShape);
        const lxmInput = new ort.Tensor('float32', toFloat32Array(sampleData.lxm_input), lxmInputShape);

        const feeds = {
            aud_input: audInput,
            mo_input: moInput,
            lxm_input: lxmInput,
        };

        const results = await session.run(feeds);

        const jsOutput = results.output.data;
        const pyOutput = toFloat32Array(sampleData.output);

        // Compare outputs
        expect(arraysClose(jsOutput, pyOutput)).toBe(true);
    });
});
